
class MyError(Exception):
    """异常抛出类"""
    pass

